-- Add gap analysis columns to users table.
-- These are generated by OpenAI during onboarding and persisted so the
-- dashboard can display them without requiring 3+ completed sessions.

alter table public.users
    add column if not exists mindset_gap         text,
    add column if not exists mindset_gap_detail  text,
    add column if not exists hunting_gap         text,
    add column if not exists hunting_gap_detail  text;
