-- =============================================================
-- TABLE 1: users
-- Extends auth.users; stores MindGym-specific profile data.
-- =============================================================

create table if not exists public.users (
    -- Primary key mirrors auth.users.id (UUID set by Supabase Auth)
    id              uuid        not null references auth.users (id) on delete cascade,

    -- Career goal the user is working toward (e.g. "Senior SWE at FAANG")
    goal            text        not null,

    -- Current career stage (e.g. "student", "mid-level", "senior")
    stage           text        not null,

    -- Self-reported anxiety level (1 = low, 10 = high)
    anxiety_level   smallint    not null check (anxiety_level between 1 and 10),

    -- Row creation timestamp; defaults to current time in UTC
    created_at      timestamptz not null default now(),

    constraint users_pkey primary key (id)
);

-- =============================================================
-- TABLE 2: jobs
-- Tracks job applications belonging to a user.
-- =============================================================

create table if not exists public.jobs (
    -- Surrogate primary key; generated by default so callers can supply their own UUID
    id              uuid        not null default gen_random_uuid(),

    -- Owning user; cascade-deletes applications when the user is removed
    user_id         uuid        not null references public.users (id) on delete cascade,

    -- Company the user applied to
    company         text        not null,

    -- Job role / title applied for
    role            text        not null,

    -- Current application status; constrained to known lifecycle values
    status          text        not null check (status in ('applied', 'screen', 'hm', 'deep', 'final', 'offer', 'closed')),

    -- When the user submitted the application (may be unknown at row creation)
    applied_at      timestamptz,

    -- Free-form notes the user wants to record about this application
    notes           text,

    -- Row creation timestamp; defaults to current time in UTC
    created_at      timestamptz not null default now(),

    constraint jobs_pkey primary key (id)
);

-- Index for the most common access pattern: fetch all jobs for a user
create index if not exists jobs_user_id_idx on public.jobs (user_id);

-- =============================================================
-- TABLE 3: meditation_sessions
-- Public library of guided meditation content; not user-specific.
-- =============================================================

create table if not exists public.meditation_sessions (
    -- Surrogate primary key
    id              uuid        not null default gen_random_uuid(),

    -- Human-readable title of the session
    title           text        not null,

    -- Category of meditation; constrained to known content types
    type            text        not null check (type in ('phone_screen', 'hm_round', 'final_round', 'negotiation', 'first_day', 'rejection_recovery', 'networking_event', 'cold_outreach')),

    -- Length of the audio in seconds
    duration_secs   integer     not null check (duration_secs > 0),

    -- URL to hosted audio file; populated in Week 2
    audio_url       text,

    -- Optional editorial description shown to users
    description     text,

    constraint meditation_sessions_pkey primary key (id)
);

-- =============================================================
-- TABLE 4: user_sessions
-- Records which meditation sessions each user has completed.
-- =============================================================

create table if not exists public.user_sessions (
    -- Surrogate primary key
    id              uuid        not null default gen_random_uuid(),

    -- User who completed the session
    user_id         uuid        not null references public.users (id) on delete cascade,

    -- The meditation session that was completed
    session_id      uuid        not null references public.meditation_sessions (id) on delete cascade,

    -- When the user finished the session; defaults to now
    completed_at    timestamptz not null default now(),

    -- Optional mood rating captured before starting (1 = very low, 10 = very high)
    mood_before     smallint    check (mood_before between 1 and 10),

    -- Optional mood rating captured after finishing (1 = very low, 10 = very high)
    mood_after      smallint    check (mood_after between 1 and 10),

    constraint user_sessions_pkey primary key (id)
);

-- Fetch a user's sessions ordered by most recent; also covers session_id FK lookups
create index if not exists user_sessions_user_id_completed_at_idx on public.user_sessions (user_id, completed_at desc);
create index if not exists user_sessions_session_id_idx           on public.user_sessions (session_id);

-- =============================================================
-- TABLE 5: streaks
-- One row per user; tracks daily engagement streak counters.
-- =============================================================

create table if not exists public.streaks (
    -- user_id is the primary key — exactly one streak record per user
    user_id         uuid        not null references public.users (id) on delete cascade,

    -- Number of consecutive active days as of last_active
    current_streak  integer     not null default 0 check (current_streak >= 0),

    -- All-time highest consecutive day count for this user
    longest_streak  integer     not null default 0 check (longest_streak >= 0),

    -- Last date the user was active; used to determine if streak should reset or increment
    last_active     timestamptz,

    constraint streaks_pkey primary key (user_id)
);

-- =============================================================
-- TABLE 6: mood_logs
-- Standalone mood check-ins recorded outside of meditation sessions.
-- =============================================================

create table if not exists public.mood_logs (
    -- Surrogate primary key
    id              uuid        not null default gen_random_uuid(),

    -- User who logged the mood check-in
    user_id         uuid        not null references public.users (id) on delete cascade,

    -- Mood score at time of check-in (1 = very low, 10 = very high)
    score           smallint    not null check (score between 1 and 10),

    -- Optional free-text note accompanying the mood entry
    note            text,

    -- When the check-in was recorded; defaults to now
    logged_at       timestamptz not null default now(),

    constraint mood_logs_pkey primary key (id)
);

-- Fetch a user's mood logs ordered by most recent
create index if not exists mood_logs_user_id_logged_at_idx on public.mood_logs (user_id, logged_at desc);

-- =============================================================
-- ROW LEVEL SECURITY
-- =============================================================

-- Step 1: Enable RLS on all tables
alter table public.users               enable row level security;
alter table public.jobs                enable row level security;
alter table public.meditation_sessions enable row level security;
alter table public.user_sessions       enable row level security;
alter table public.streaks             enable row level security;
alter table public.mood_logs           enable row level security;

-- Step 2: Policies
-- auth.uid() is wrapped in (SELECT ...) to prevent per-row re-evaluation.

-- users: own profile only
create policy "users: own profile"
    on public.users for all
    using      ((select auth.uid()) = id)
    with check ((select auth.uid()) = id);

-- jobs: own rows only
create policy "jobs: own rows"
    on public.jobs for all
    using      ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

-- meditation_sessions: public read, no writes via client
create policy "meditation_sessions: public read"
    on public.meditation_sessions for select
    using (true);

-- user_sessions: own rows only
create policy "user_sessions: own rows"
    on public.user_sessions for all
    using      ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

-- streaks: own row only
create policy "streaks: own row"
    on public.streaks for all
    using      ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

-- mood_logs: own rows only
create policy "mood_logs: own rows"
    on public.mood_logs for all
    using      ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);
